# Generated by Django 5.2.4 on 2025-08-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_entry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="date_added",
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ManyToManyField(related_name="posts", to="blogs.topic"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Entry",
        ),
    ]
