# Generated by Django 5.2.4 on 2025-08-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_remove_topic_date_added_blogpost_delete_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
